### ISSUE TITLE
Just prints invalid token everytime

### ISSUE THREAD

**Issue by UNITY002** [Smug246/Discord-Mass-Pinger#1]
Just prints invalid token every time, Fix it before publishing it

**Comment by Smug246** [comment]
before u say something like that why don't u check ur using the right version of discord.py (1.73) not (2.00). Also just to be clear u r using ur own token right not a bots token

**Comment by UNITY002** [comment]
I've done all the things which are supposed to do, and I did tried both a bot token and a user token.
